query MediaItems($dir: String!) {
  mediaItems(dir: $dir) {
    key
    type
  }
}

mutation CreateMediaUpload($key: String!) {
  uploadUrl: createMediaUpload(key: $key)
}

mutation DeleteMedia($key: String!) {
  deleteMedia(key: $key)
}
