fragment StorableAuthToken on AuthToken {
  token
  user {
    id
    roles {
      id
      name
      permissions
    }
  }
}

mutation CreateAuthTokenGoogle($googleIdToken: String!) {
  authToken: createAuthTokenGoogle(
    googleIdToken: $googleIdToken
    clientType: WEB
  ) {
    ...StorableAuthToken
  }
}

mutation CreateAuthTokenLocal($username: String!, $password: String!) {
  authToken: createAuthTokenLocal(username: $username, password: $password) {
    ...StorableAuthToken
  }
}

query Config {
  config {
    createAnonymousUsers
  }
}

mutation CreateUser($email: String!, $username: String!, $password: String!) {
  createUser(email: $email, username: $username, password: $password) {
    id
  }
}
