extend type Query {
  authToken(params: AuthTokenParams!): AuthToken!
}

# only one field may/must be provided
input AuthTokenParams {
  google: AuthTokenGoogleParams
  local: AuthTokenLocalParams
  # requires ADMIN_USERS permission
  userId: ID
}

input AuthTokenGoogleParams {
  idToken: String!
}

input AuthTokenLocalParams {
  username: String!
  password: String!
}

type AuthToken {
  token: String!
  userId: ID!
  user: User!
}

enum AuthPermission {
  ADMIN_MEDIA
  ADMIN_NOTES
  ADMIN_STEAM
  ADMIN_ROLES
  ADMIN_USERS
  MEDIA
  NOTES
  PROJECTS
}
