extend type Mutation {
  createAuthTokenGoogle(
    googleIdToken: String!,
    clientType: AuthClientType!
  ): AuthToken!
  # username can also be email
  createAuthTokenLocal(username: String!, password: String!): AuthToken!
  # requires auth
  createAuthToken(userId: String!): AuthToken!
}

enum AuthClientType {
  MOBILE
  WEB
}

type AuthToken {
  token: String!
  userId: ID!
  user: User!
}

enum AuthPermission {
  MANAGE_MEDIA_SELF
  MANAGE_MEDIA_ALL
  MANAGE_NOTES_SELF
  MANAGE_NOTES_ALL
  MANAGE_ROLES
  MANAGE_STEAM_GAMES
  MANAGE_USERS
  TRANSCRIPTIONS
}
