extend type Mutation {
  addMediaDownload(url: String!, destinationKey: String!): Progress!
  createMedia(key: String!, data: String!): Boolean!
  createMediaUpload(key: String!): String!
}

extend type Query {
  mediaItems(dir: String!): [MediaItem!]!
}

type MediaItem {
  key: String!
  type: MediaItemType!
}

enum MediaItemType {
  FILE
  DIRECTORY
  SERIES
}
