extend type Mutation {
  addMediaDownload(url: String!, destinationKey: String!, sync: Boolean): Progress!
  createMedia(key: String!, data: String!): Boolean!
  # returns a URL - POST the file body to it
  createMediaUpload(key: String!): String!
  deleteMedia(key: String!): Boolean!
}

extend type Query {
  mediaItem(key: String!): MediaItem
}

type MediaItem {
  key: String!
  type: MediaItemType!
  "Duration of this media in seconds. Only set for video and audio files."
  duration: Int
  children: [MediaItem!]
}

enum MediaItemType {
  FILE
  DIRECTORY
  SERIES
}
