extend type Mutation {
  # filename is inferred from the input media key
  startTranscription(mediaKey: String!): Transcription!
}

extend type Query {
  transcriptions: [Transcription!]!
}

type Transcription {
  id: ID!
  status: TranscriptionStatus!
  filename: String!
  # the output sheet music PDF is stored here, see MediaItem.url to get it
  pdf: MediaItem
}

enum TranscriptionStatus {
  CREATED
  STARTED
  COMPLETE
  ERRORED
}
