extend type Mutation {
  createNote(title: String!): Note!
  removeNote(id: ID!): Boolean!
  updateNoteBody(id: ID!, body: String!): Boolean!
}

extend type Query {
  note(id: ID!): Note!
  notes: [Note!]!
}

type Note {
  id: ID!
  createdAt: DateTime!
  title: String!
  body: String!
}
