extend type Query {
  progress(id: ID!): Progress!
  progresses(ids: [ID!]!): [Progress!]!
}

type Progress {
  id: ID!
  action: String!
  createdAt: DateTime!
  status: ProgressStatus!
  logs: [ProgressLog!]!
}

type ProgressLog {
  createdAt: DateTime!
  text: String!
}

enum ProgressStatus {
  CREATED
  IN_PROGRESS
  COMPLETE
  ERRORED
}
