extend type Query {
  progress(id: String!): Progress!
  progresses(ids: [String!]!): [Progress!]!
}

type Progress {
  _id: String!
  action: String!
  createdAt: DateTime!
  status: ProgressStatus!
  logs: [ProgressLog!]!
}

type ProgressLog {
  createdAt: DateTime!
  text: String!
}

enum ProgressStatus {
  CREATED
  IN_PROGRESS
  COMPLETE
  ERRORED
}
