type Mutation {
  addRoleToUser(userId: ID!, roleId: ID!): Boolean!
  createUser(email: String!, username: String, password: String): User!
  setUserPassword(userId: ID!, password: String!): Boolean!
}

type Query {
  user(id: ID): User!
  users: [User!]!
}

type User {
  id: ID!
  email: String!
  username: String
  roles: [Role!]
  permissions: [AuthPermission!]
}
