type Mutation {
  createUser(params: CreateUserParams!): User!
  updateUser(params: UpdateUserParams!): Boolean!
}

type Query {
  user(id: ID): User!
  users: [User!]!
}

type User {
  id: ID!
  email: String!
  username: String
  roles: [Role!]
  permissions: [AuthPermission!]
}

input CreateUserParams {
  email: String!
  username: String
  password: String
}

input UpdateUserParams {
  id: ID!
  email: String
  username: String
  password: String
  roleIds: [ID!]
}
