mutation CreateNote($title: String!) {
  createNote(title: $title) {
    id
  }
}

mutation RemoveNote($id: ID!) {
  removeNote(id: $id)
}

mutation UpdateNoteBody($id: ID!, $body: String!) {
  updateNoteBody(id: $id, body: $body)
}

fragment ListNote on Note {
  id
  createdAt
  title
}

query Note($id: ID!) {
  note(id: $id) {
    ...ListNote
    body
  }
}

query Notes {
  notes {
    ...ListNote
  }
}
