query getBaseMediaItem($key: String!) {
  mediaItem(key: $key) {
    ...BaseMediaItem
  }
}

query getDeepMediaItem($key: String!) {
  mediaItem(key: $key) {
    ...DeepMediaItem
  }
}

mutation createMediaUpload($key: String!) {
  uploadUrl: createMediaUpload(key: $key)
}

mutation deleteMedia($key: String!) {
  deleteMedia(key: $key)
}

mutation addMediaDownload($url: String!, $destinationKey: String!, $sync: Boolean!) {
  progress: addMediaDownload(url: $url, destinationKey: $destinationKey, sync: $sync) {
    id
  }
}

mutation createMedia($key: String!, $data: String!) {
  created: createMedia(key: $key, data: $data)
}

fragment BaseMediaItem on MediaItem {
  key
  type
  children {
    key
    type
    duration
  }
}

fragment DeepMediaItem on MediaItem {
  key
  type
  children {
    key
    type
    children {
      key
      type
    }
  }
}
