mutation updateProjectConfig($params: UpdateProjectConfigParams!) {
  updated: updateProjectConfig(params: $params)
}

mutation deleteProjectConfig($adapterType: ProjectAdapterType!) {
  deleted: deleteProjectConfig(adapterType: $adapterType)
}

query getProjectConfigs {
  user {
    projectConfigs {
      ...ProjectConfig
      apiToken
    }
  }
}

query getProjectBoards($adapterType: ProjectAdapterType!) {
  project(adapterType: $adapterType) {
    config {
      ...ProjectConfig
    }
    boards {
      ...ProjectBoard
    }
  }
}

query getProjectBoard($adapterType: ProjectAdapterType!, $boardId: Int!) {
  project(adapterType: $adapterType) {
    config {
      ...ProjectConfig
    }
    boards {
      ...ProjectBoard
    }
    sprints(boardId: $boardId) {
      ...ProjectSprint
    }
  }
}

query getProjectSprint($adapterType: ProjectAdapterType!, $boardId: Int!, $sprintId: Int!) {
  project(adapterType: $adapterType) {
    config {
      ...ProjectConfig
    }
    boards {
      ...ProjectBoard
    }
    sprints(boardId: $boardId) {
      ...ProjectSprint
    }
    issues(sprintId: $sprintId) {
      ...ProjectIssue
    }
  }
}

fragment ProjectConfig on ProjectConfig {
  adapterType
  host
  email
}

fragment ProjectBoard on ProjectBoard {
  id
  name
}

fragment ProjectSprint on ProjectSprint {
  id
  name
  state
  start
  end
}

fragment ProjectIssue on ProjectIssue {
  id
  key
  type
  state
  title
  storyPoints
  implementer {
    id
    name
    email
  }
  sprints {
    ...ProjectSprint
  }
  statusDurations {
    status
    workingDays
    workingDuration
    fullDuration
  }
}
