query projectConfigs {
  user {
    projectConfigs {
      adapterType
      host
      email
      apiToken
    }
  }
}

mutation updateProjectConfig($params: UpdateProjectConfigParams!) {
  updated: updateProjectConfig(params: $params)
}

mutation deleteProjectConfig($adapterType: ProjectAdapterType!) {
  deleted: deleteProjectConfig(adapterType: $adapterType)
}

query projectBoards($adapterType: ProjectAdapterType!) {
  project(adapterType: $adapterType) {
    config {
      adapterType
    }
    boards {
      id
      name
    }
  }
}

query projectSprints($adapterType: ProjectAdapterType!, $boardId: Int!) {
  project(adapterType: $adapterType) {
    config {
      adapterType
    }
    sprints(boardId: $boardId) {
      ...ProjectSprintFragment
    }
  }
}

query projectIssues($adapterType: ProjectAdapterType!, $sprintId: Int!) {
  project(adapterType: $adapterType) {
    config {
      adapterType
    }
    issues(sprintId: $sprintId) {
      id
      key
      type
      state
      title
      storyPoints
      implementer {
        id
        name
        email
      }
      sprints {
        ...ProjectSprintFragment
      }
      statusDurations {
        status
        workingDays
        workingDuration
        fullDuration
      }
    }
  }
}

fragment ProjectSprintFragment on ProjectSprint {
  id
  name
  state
  start
  end
}
