name: API
run-name: ${{ github.ref_type == 'tag' && 'Publish' || 'Build' }} ${{ github.ref_type == 'tag' && github.ref_name || 'API' }}
on:
  push:
    branches: '*'
    tags:
      - v*
      - api-*
    paths:
      - .github/workflows/*
      - api/**
      - sdk/**

permissions:
  contents: read
  packages: write

jobs:
  tests:
    uses: ./.github/workflows/tests.yml
    with:
      directory: api

  publish:
    if: ${{ github.ref_type == 'tag' }}
    needs: tests
    uses: ./.github/workflows/publish-docker.yml
    with:
      directory: api
      tag: ghcr.io/aldahick/rex-api
