name: publish-web
on:
  push:
    tags:
      - web-v**
jobs:
  publish-web:
    uses: ./.github/workflows/publish-image.yml
    with:
      directory: web
      imageName: aldahick/rex-web
    secrets:
      dockerUsername: ${{ secrets.DOCKER_USERNAME }}
      dockerPassword: ${{ secrets.DOCKER_PASSWORD }}
