name: publish-image
on:
  workflow_call:
    inputs:
      copySchema:
        required: false
        default: false
        type: boolean
      dockerfile:
        required: true
        type: string
      directory:
        required: true
        type: string
      installReactUtils:
        required: false
        default: false
        type: boolean
      imageName:
        required: true
        type: string
    secrets:
      githubToken:
        required: true
jobs:
  publish-package:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - if: ${{ inputs.installReactUtils }}
        run: npm i @athenajs/react-utils
      - if: ${{ inputs.copySchema }}
        run: cp -r gql api/gql
      - uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.githubToken }}
      - id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ inputs.imageName }}
      - uses: docker/build-push-action@v3
        with:
          context: ${{ inputs.directory }}
          file: ${{ inputs.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
