name: publish-image
on:
  workflow_call:
    inputs:
      copySchema:
        required: false
        default: false
        type: boolean
      dockerfile:
        required: true
        type: string
      directory:
        required: true
        type: string
      installReactUtils:
        required: false
        default: false
        type: boolean
      imageName:
        required: true
        type: string
    secrets:
      githubToken:
        required: true

jobs:
  build-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - if: ${{ inputs.installReactUtils }}
        run: npm i @athenajs/react-utils
      - if: ${{ inputs.copySchema }}
        run: cp -r gql api/gql
      - uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64
      - uses: docker/setup-buildx-action@v2
      - id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ inputs.imageName }}
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.githubToken }}
      - name: Build digest
        id: build
        uses: docker/build-push-action@v3
        with:
          file: ${{ inputs.dockerfile }}
          context: ${{ inputs.directory }}
          platforms: ${{ matrix.platform }}
          outputs: type=image,name=${{ inputs.imageName }},push-by-digest=true,name-canonical=true,push=true
          push: true
          labels: ${{ steps.meta.outputs.labels }}
      - name: Export digest
        run: |
          mkdir -p /tmp/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "/tmp/digests/${digest#sha256:}"
      - name: Upload digest
        uses: actions/upload-artifact@v3
        with:
          name: digests
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1

  merge-publish:
    runs-on: ubuntu-latest
    needs: build-image
    steps:
      - name: Download digests
        uses: actions/download-artifact@v3
        with:
          name: digests
          path: /tmp/digests
      - uses: docker/setup-buildx-action@v2
      - id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ inputs.imageName }}
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.githubToken }}
      - name: Create manifest list and push
        working-directory: /tmp/digests
        run: |
          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf '${{ inputs.imageName }}@sha256:%s ' *)
