name: publish-web
on:
  push:
    tags:
      - web-v**
      - v*
jobs:
  publish-web:
    uses: ./.github/workflows/publish-image.yml
    with:
      directory: web
      dockerfile: node_modules/@athenajs/react-utils/Dockerfile
      imageName: ghcr.io/aldahick/rex-web
      installReactUtils: true
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}
