name: publish-api
on:
  push:
    tags:
      - api-v*
jobs:
  publish-api:
    uses: ./.github/workflows/publish-image.yml
    with:
      directory: api
      imageName: ghcr.io/aldahick/rex-api
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}
