name: publish-api
on:
  push:
    tags:
      - api-v*
jobs:
  publish-api:
    uses: ./.github/workflows/publish-image.yml
    with:
      directory: api
      imageName: aldahick/rex-api
    secrets:
      dockerUsername: ${{ secrets.DOCKER_USERNAME }}
      dockerPassword: ${{ secrets.DOCKER_PASSWORD }}
