name: publish-web
on:
  push:
    tags:
      - web-v**
jobs:
  publish-web:
    uses: ./.github/workflows/publish-image.yml
    with:
      directory: web
      imageName: ghcr.io/aldahick/rex-web
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}
