name: publish-api
on:
  push:
    tags:
      - api-v*
      - v*
jobs:
  publish-api:
    uses: ./.github/workflows/publish-image.yml
    with:
      copySchema: true
      directory: api
      dockerfile: api/Dockerfile
      imageName: ghcr.io/aldahick/rex-api
    secrets:
      githubToken: ${{ secrets.GITHUB_TOKEN }}
