name: publish-image
on:
  workflow_call:
    inputs:
      copySchema:
        required: false
        default: false
        type: boolean
      dockerfile:
        required: false
        default: Dockerfile
        type: string
      imageName:
        required: true
        type: string
      directory:
        required: true
        type: string
    secrets:
      githubToken:
        required: true
jobs:
  publish-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm i @athenajs/react-utils # only needed for web but doesn't hurt for api
      - uses: docker/login-action@v2.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.githubToken }}
      - id: meta
        uses: docker/metadata-action@v4.1.1
        with:
          images: ${{ inputs.imageName }}
      - if: ${{ inputs.copySchema }}
        run: cp -r gql api/gql
      - uses: docker/build-push-action@v3.2.0
        with:
          context: ${{ inputs.directory }}
          file: ${{ inputs.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
