name: publish-image
on:
  workflow_call:
    inputs:
      copySchema:
        required: false
        default: false
        type: boolean
      imageName:
        required: true
        type: string
      directory:
        required: true
        type: string
    secrets:
      dockerUsername:
        required: true
      dockerPassword:
        required: true
jobs:
  publish-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.dockerUsername }}
          password: ${{ secrets.dockerPassword }}
      - id: meta
        uses: docker/metadata-action@v4.1.1
        with:
          images: ${{ inputs.imageName }}
      - if: ${{ inputs.copySchema }}
        run: cp -r gql api/gql
      - uses: docker/build-push-action@v3.2.0
        with:
          context: ${{ inputs.directory }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
